name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Check Flag
       run: |
         if [["$FLAG" == "true" ]]; then
           echo "Flag is set. Proceeding with the workflow."
         else
           echo "Flag is not set. Skipping the workflow."
           exit 78
         fi
